# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
let
  bindMount = path: {
    device = builtins.toString path;
    options = ["bind"];
  };
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # fileSystems."/" =
  #   { device = "/dev/disk/by-uuid/4473c8f2-f123-43bb-9a93-6a457f387f3f";
  #     fsType = "ext4";
  #   };
  fileSystems."/" = {
    fsType = "tmpfs";
  };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/713dd0bc-4f20-4783-a5df-31e725136faa";
      fsType = "ext4";
    };
  fileSystems."/nix/persist" =
    { device = "/dev/disk/by-uuid/3e7f0b86-c914-45d7-9ab7-cae2669bd250";
      fsType = "btrfs";
      neededForBoot = true;
      autoFormat = true;
    };
  fileSystems."/home" = bindMount /nix/persist2/home;
  fileSystems."/root" = bindMount /nix/persist2/root2;
  fileSystems."/etc/nixos" = bindMount /nix/persist2/nixos;
  fileSystems."/var/lib" = bindMount /nix/persist2/var;

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0EE0-12DA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/win" =
    { device = "/dev/disk/by-uuid/8794880b-1500-4989-af84-d82ab1340326";
      fsType = "ext2";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
